# Generated by Django 4.0.6 on 2022-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xPerHour', models.TextField()),
                ('RSSIy', models.FloatField()),
                ('RSRPy', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
