# Generated by Django 4.0.6 on 2022-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssigraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.TextField(),
        ),
    ]
